name: Create source

on:
    workflow_dispatch:
        inputs:
            id:
                description: ID (e.g. release-test)
                required: true
                type: string
            name:
                description: Name (e.g. Release Test)
                required: true
                type: string
            access-level:
                description: Access level (e.g. internal)
                required: true
                type: choice
                options:
                    - internal
                    - internal-confidential
                    - external
                    - external-confidential
            description:
                description:
                    Longer description (e.g. Versions we intend to release next)
                required: true
                type: string

jobs:
    create-source:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: 22
                  cache: npm
            - run: npm ci
            - env:
                  ARTIFACTORY_TOKEN:
                      ${{ secrets.COM_NORDICSEMI_FILES_PASSWORD_SWTOOLS_FRONTEND
                      }}
              run: |
                  npm run create-source -- \
                    --id '${{ inputs.id }}' \
                    --access-level '${{ inputs.access-level  }}' \
                    --name '${{ inputs.name }}' \
                    --description '${{ inputs.description }}'
